"""
config.py – Central configuration for the Stock Research Assistant.

All environment variables are read here; the rest of the codebase imports
only from this module so that changing a key/path is done in one place.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load .env file from the project root (same directory as this file)
_PROJECT_ROOT = Path(__file__).parent
load_dotenv(_PROJECT_ROOT / ".env")

# ── API keys ───────────────────────────────────────────────────────────────────
GEMINI_API_KEY: str = os.environ.get("GEMINI_API_KEY", "")
TAVILY_API_KEY: str = os.environ.get("TAVILY_API_KEY", "")

# ── LLM settings ──────────────────────────────────────────────────────────────
LLM_MODEL: str = os.environ.get("LLM_MODEL", "gemini-flash-lite-latest")
LLM_TEMPERATURE: float = float(os.environ.get("LLM_TEMPERATURE", "0"))

# ── ReAct agent guardrail ─────────────────────────────────────────────────────
MAX_ITERATIONS: int = int(os.environ.get("MAX_ITERATIONS", "10"))

# ── RAG / Vector store ────────────────────────────────────────────────────────
VECTOR_STORE_PATH: str = os.environ.get(
    "VECTOR_STORE_PATH",
    str(_PROJECT_ROOT / "rag" / "vectorstore"),
)
RAG_DOCS_PATH: str = str(_PROJECT_ROOT / "rag" / "documents")
RAG_CHUNK_SIZE: int = 600
RAG_CHUNK_OVERLAP: int = 80
RAG_TOP_K: int = 4

# ── MCP Server ────────────────────────────────────────────────────────────────
MCP_SERVER_SCRIPT: str = str(_PROJECT_ROOT / "mcp_server" / "stock_mcp_server.py")

# ── Forbidden output words (guardrail) ────────────────────────────────────────
FORBIDDEN_WORDS: list[str] = ["buy", "sell", "purchase", "short", "price target"]

# ── Disclaimer ────────────────────────────────────────────────────────────────
DISCLAIMER: str = (
    "\n\n---\n"
    "⚠️  **Disclaimer:** This research note is generated by an AI assistant for "
    "educational purposes only. It is NOT investment advice and should NOT be used "
    "as the sole basis for any financial decision. Always consult a SEBI-registered "
    "financial advisor before investing. Past performance does not guarantee future results."
)

def validate_config() -> None:
    """Raise an error early if required keys are missing."""
    missing = []
    if not GEMINI_API_KEY:
        missing.append("GEMINI_API_KEY")
    if not TAVILY_API_KEY:
        missing.append("TAVILY_API_KEY")
    if missing:
        raise EnvironmentError(
            f"Missing required environment variables: {', '.join(missing)}. "
            "Please copy .env.example to .env and fill in the values."
        )
